document.write('<nav id="sidebar">\n');
document.write('  <div class="sidebar-header">\n');
document.write("    <h4>TỔNG QUAN</h4>\n");
document.write("  </div>\n");
document.write("\n");
document.write('  <div class="sidebar-muc">\n');
document.write("    <h6>Quản lý KPI</h6>\n");
document.write("  </div>\n");
document.write("\n");
document.write('  <ul class="list-unstyled components">\n');
document.write('    <li class="active">\n');
document.write("      <a\n");
document.write('        href="#homeSubmenu"\n');
document.write('        data-toggle="collapse"\n');
document.write('        aria-expanded="false"\n');
document.write('        class="dropdown-toggle"\n');
document.write("      >\n");
document.write('        <i class="fas fa-home"></i>\n');
document.write("        Thông tin tổng quan KPI\n");
document.write("      </a>\n");
document.write('      <ul class="collapse list-unstyled" id="homeSubmenu">\n');
document.write("        <li>\n");
document.write("          <a\n");
document.write('          href="#"\n');
document.write('          >\n');
document.write('          <i class="fas fa-signal"></i>\n');
document.write('             Tần suất\n');
document.write('          </a>\n');
document.write("        </li>\n");
document.write("        <li>\n");
document.write("          <a\n");
document.write('          href="#"\n');
document.write('          >\n');
document.write('          <i class="fas fa-location-arrow"></i>\n');
document.write('             Chiều hướng\n');
document.write('          </a>\n');
document.write("        </li>\n");
document.write("        <li>\n");
document.write("          <a\n");
document.write('          href="#"\n');
document.write('          >\n');
document.write('          <i class="fas fa-flag"></i>\n');
document.write('             Hệ số hoàn thành\n');
document.write('          </a>\n');
document.write("        </li>\n");
document.write("      </ul>\n");
document.write("    </li>\n");
document.write('    <li class="active">\n');
document.write("      <a\n");
document.write('        href="#homeKPI"\n');
document.write('        data-toggle="collapse"\n');
document.write('        aria-expanded="false"\n');
document.write('        class="dropdown-toggle"\n');
document.write("      >\n");
document.write('        <i class="fas fa-anchor"></i>\n');
document.write("        KPI của từng bộ phận\n");
document.write("      </a>\n");
document.write('      <ul class="collapse list-unstyled" id="homeKPI">\n');
document.write("        <li>\n");
document.write("          <a\n");
document.write('          href="#"\n');
document.write('          >\n');
document.write('          <i class="fas fa-signal"></i>\n');
document.write('             Sản xuất\n');
document.write('          </a>\n');
document.write("        </li>\n");
document.write("        <li>\n");
document.write("          <a\n");
document.write('          href="#"\n');
document.write('          >\n');
document.write('          <i class="fas fa-location-arrow"></i>\n');
document.write('             Kinh doanh\n');
document.write('          </a>\n');
document.write("        </li>\n");
document.write("        <li>\n");
document.write("          <a\n");
document.write('          href="#"\n');
document.write('          >\n');
document.write('          <i class="fas fa-flag"></i>\n');
document.write('             Tài chính\n');
document.write('          </a>\n');
document.write("        </li>\n");
document.write("        <li>\n");
document.write("          <a\n");
document.write('          href="#"\n');
document.write('          >\n');
document.write('          <i class="fas fa-flag"></i>\n');
document.write('             Kế toán\n');
document.write('          </a>\n');
document.write("        </li>\n");
document.write("        <li>\n");
document.write("          <a\n");
document.write('          href="#"\n');
document.write('          >\n');
document.write('          <i class="fas fa-flag"></i>\n');
document.write('             Kiểm định\n');
document.write('          </a>\n');
document.write("        </li>\n");
document.write("      </ul>\n");
document.write("    </li>\n");
document.write("    <li>\n");
document.write('      <a href="#">\n');
document.write('        <i class="fas fa-briefcase"></i>\n');
document.write("        Thiết lập KPI\n");
document.write("      </a>\n");
document.write("  </ul>\n");
document.write("\n");

document.write('  <div class="sidebar-muc">\n');
document.write("    <h6>Marketing</h6>\n");
document.write("  </div>\n");
document.write("\n");
document.write('  <ul class="list-unstyled components">\n');
document.write('    <li class="active">\n');
document.write("      <a\n");
document.write('        href="#customerList"\n');
document.write('        data-toggle="collapse"\n');
document.write('        aria-expanded="false"\n');
document.write('        class="dropdown-toggle"\n');
document.write("      >\n");
document.write('        <i class="fas fa-home"></i>\n');
document.write("        Khách hàng\n");
document.write("      </a>\n");
document.write('      <ul class="collapse list-unstyled" id="customerList">\n');
document.write("        <li>\n");
document.write("          <a\n");
document.write('          href="#"\n');
document.write('          >\n');
document.write('          <i class="fas fa-signal"></i>\n');
document.write('             Danh sách khách hàng\n');
document.write('          </a>\n');
document.write("        </li>\n");
document.write("        <li>\n");
document.write("          <a\n");
document.write('          href="#"\n');
document.write('          >\n');
document.write('          <i class="fas fa-location-arrow"></i>\n');
document.write('             Phân loại khác hàng\n');
document.write('          </a>\n');
document.write("        </li>\n");
document.write("        <li>\n");
document.write("          <a\n");
document.write('          href="#"\n');
document.write('          >\n');
document.write('          <i class="fas fa-flag"></i>\n');
document.write('             Bộ lọc\n');
document.write('          </a>\n');
document.write("        </li>\n");
document.write("      </ul>\n");
document.write("    </li>\n");
document.write('    <li class="active">\n');
document.write("      <a\n");
document.write('        href="#coupon"\n');
document.write('        data-toggle="collapse"\n');
document.write('        aria-expanded="false"\n');
document.write('        class="dropdown-toggle"\n');
document.write("      >\n");
document.write('        <i class="fas fa-anchor"></i>\n');
document.write("        Tạo chương trình KM\n");
document.write("      </a>\n");
document.write('      <ul class="collapse list-unstyled" id="coupon">\n');
document.write("        <li>\n");
document.write("          <a\n");
document.write('          href="#"\n');
document.write('          >\n');
document.write('          <i class="fas fa-signal"></i>\n');
document.write('             Tạo tự động\n');
document.write('          </a>\n');
document.write("        </li>\n");
document.write("        <li>\n");
document.write("          <a\n");
document.write('          href="#"\n');
document.write('          >\n');
document.write('          <i class="fas fa-location-arrow"></i>\n');
document.write('             Tùy chỉnh chương trình KM\n');
document.write('          </a>\n');
document.write("        </li>\n");
document.write("        <li>\n");
document.write("          <a\n");
document.write('          href="#"\n');
document.write('          >\n');
document.write('          <i class="fas fa-flag"></i>\n');
document.write('             Tùy chỉnh tự động nhắn tin\n');
document.write('          </a>\n');
document.write("        </li>\n");
document.write("        <li>\n");
document.write("          <a\n");
document.write('          href="#"\n');
document.write('          >\n');
document.write('          <i class="fas fa-flag"></i>\n');
document.write('             Đồng bộ chương trình KM\n');
document.write('          </a>\n');
document.write("        </li>\n");
document.write("      </ul>\n");
document.write("    </li>\n");
document.write("    <li>\n");
document.write('    <li class="active">\n');
document.write("      <a\n");
document.write('        href="#greetingCard"\n');
document.write('        data-toggle="collapse"\n');
document.write('        aria-expanded="false"\n');
document.write('        class="dropdown-toggle"\n');
document.write("      >\n");
document.write('        <i class="fas fa-anchor"></i>\n');
document.write("        Gửi thiệp chúc mừng\n");
document.write("      </a>\n");
document.write('      <ul class="collapse list-unstyled" id="greetingCard">\n');
document.write("        <li>\n");
document.write("          <a\n");
document.write('          href="#"\n');
document.write('          >\n');
document.write('          <i class="fas fa-signal"></i>\n');
document.write('             Tạo thiệp chúc mừng\n');
document.write('          </a>\n');
document.write("        </li>\n");
document.write("        <li>\n");
document.write("          <a\n");
document.write('          href="#"\n');
document.write('          >\n');
document.write('          <i class="fas fa-location-arrow"></i>\n');
document.write('             Thiết lập phương thức gửi\n');
document.write('          </a>\n');
document.write("        </li>\n");
document.write("        <li>\n");
document.write("      </ul>\n");
document.write("    </li>\n");
document.write("    <li>\n");
document.write("  </ul>\n");
document.write("\n");
document.write('  <ul class="list-unstyled CTAs">\n');
document.write("    <li>\n");
document.write("      <a\n");
document.write(
  '        href="https://bootstrapious.com/tutorial/files/sidebar.zip"\n'
);
document.write('        class="download"\n');
document.write("        >Download source</a\n");
document.write("      >\n");
document.write("    </li>\n");
document.write("    <li>\n");
document.write(
  '      <a href="https://bootstrapious.com/p/bootstrap-sidebar" class="article"\n'
);
document.write("        >Back to article</a\n");
document.write("      >\n");
document.write("    </li>\n");
document.write("  </ul>\n");
document.write("</nav>\n");
