document.write('<nav id="sidebar">\n');
document.write('  <div class="sidebar-header">\n');
document.write("    <h3>Bootstrap Sidebar</h3>\n");
document.write("    <strong>BS</strong>\n");
document.write("  </div>\n");
document.write("\n");
document.write('  <ul class="list-unstyled components">\n');
document.write('    <li class="active">\n');
document.write("      <a\n");
document.write('        href="#homeSubmenu"\n');
document.write('        data-toggle="collapse"\n');
document.write('        aria-expanded="false"\n');
document.write('        class="dropdown-toggle"\n');
document.write("      >\n");
document.write('        <i class="fas fa-home"></i>\n');
document.write("        Home\n");
document.write("      </a>\n");
document.write('      <ul class="collapse list-unstyled" id="homeSubmenu">\n');
document.write("        <li>\n");
document.write('          <a href="#">Home 1</a>\n');
document.write("        </li>\n");
document.write("        <li>\n");
document.write('          <a href="#">Home 2</a>\n');
document.write("        </li>\n");
document.write("        <li>\n");
document.write('          <a href="#">Home 3</a>\n');
document.write("        </li>\n");
document.write("      </ul>\n");
document.write("    </li>\n");
document.write("    <li>\n");
document.write('      <a href="#">\n');
document.write('        <i class="fas fa-briefcase"></i>\n');
document.write("        About\n");
document.write("      </a>\n");
document.write("      <a\n");
document.write('        href="#pageSubmenu"\n');
document.write('        data-toggle="collapse"\n');
document.write('        aria-expanded="false"\n');
document.write('        class="dropdown-toggle"\n');
document.write("      >\n");
document.write('        <i class="fas fa-copy"></i>\n');
document.write("        Pages\n");
document.write("      </a>\n");
document.write('      <ul class="collapse list-unstyled" id="pageSubmenu">\n');
document.write("        <li>\n");
document.write('          <a href="#">Page 1</a>\n');
document.write("        </li>\n");
document.write("        <li>\n");
document.write('          <a href="#">Page 2</a>\n');
document.write("        </li>\n");
document.write("        <li>\n");
document.write('          <a href="#">Page 3</a>\n');
document.write("        </li>\n");
document.write("      </ul>\n");
document.write("    </li>\n");
document.write("    <li>\n");
document.write('      <a href="#">\n');
document.write('        <i class="fas fa-image"></i>\n');
document.write("        Portfolio\n");
document.write("      </a>\n");
document.write("    </li>\n");
document.write("    <li>\n");
document.write('      <a href="#">\n');
document.write('        <i class="fas fa-question"></i>\n');
document.write("        FAQ\n");
document.write("      </a>\n");
document.write("    </li>\n");
document.write("    <li>\n");
document.write('      <a href="#">\n');
document.write('        <i class="fas fa-paper-plane"></i>\n');
document.write("        Contact\n");
document.write("      </a>\n");
document.write("    </li>\n");
document.write("  </ul>\n");
document.write("\n");
document.write('  <ul class="list-unstyled CTAs">\n');
document.write("    <li>\n");
document.write("      <a\n");
document.write(
  '        href="https://bootstrapious.com/tutorial/files/sidebar.zip"\n'
);
document.write('        class="download"\n');
document.write("        >Download source</a\n");
document.write("      >\n");
document.write("    </li>\n");
document.write("    <li>\n");
document.write(
  '      <a href="https://bootstrapious.com/p/bootstrap-sidebar" class="article"\n'
);
document.write("        >Back to article</a\n");
document.write("      >\n");
document.write("    </li>\n");
document.write("  </ul>\n");
document.write("</nav>\n");
